version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
    - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment
  rso-payments:
    image: jp8874/rso-teamlj-payments:2.0
    ports:
    - 8083:8083
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://172.17.0.1:5435/payment
      KUMULUZEE_DATASOURCES0_USERNAME: postgres
      KUMULUZEE_DATASOURCES0_PASSWORD: postgres
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://172.17.0.1:2379
    depends_on:
    - postgres

