kumuluzee:
  name: rso-payments
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/PaymentDS
      connection-url: jdbc:postgresql://35.228.47.159:5432/payment
      username: rso
      password: rso
      #connection-url: jdbc:postgresql://localhost:5435/payment
      #username: postgres
      #password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
  metrics:
    web-instrumentation:
    - name: payment-endpoint
      url-pattern: /v1/payments/*
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/PaymentDS
      disk-space-health-check:
        threshold: 100000000
#      etcd-health-check:
#        connection-url: http://localhost:2379/health
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="payments">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="5d872f8f-f02a-4f15-b966-e8796ff99a28-ls.logit.io"
                              port="13221" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'

